### PR TITLE
Add ElectrumX Raw Transaction Details method and tests

### PR DESCRIPTION
**Pull request by zh**
**Issue** #4

* Added `txData()` method to the `Electrumx` class in the `electrumx.js` file
* `api-doc` documentation and examples added
* Integration tests for both `mainnet` and `testnet` added
* Unit tests and mocks added

### CODE REVIEW

**Comment by christroutner** [comment]
Hmm... ya, I'm seeing several merge conflicts. Sorry about that @zh. That wouldn't have happened if I had reviewed your previous PR sooner.

Would you mind fixing the merge conflicts and committing them?

**Comment by zh** [comment]
rebased and all conflicts fixed

**Review by christroutner — APPROVED** [review]

**Comment by christroutner** [comment]
Bounty rewarded. TXID:
88299b4b606929cb2f82cc8805b055b1cbc7c10740692dc3def0e09567b06df0

**Pull request merged**
